# ansible-playbook ./web_config.yml -e ansible_hosts=youransibledefinedhostnames
- name: Set Web Parameters
  hosts: "{{ansible_hosts}}"  # pass as -e ansible_hosts=wti_demo on the commandline
  collections:
     - wti.remote
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - cpm_web_config:
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"
      interface: "eth0"
      trace: 0
      ocsp: 0
      webterm: 0
      httpenable: 1
      httpport:  80
      httpsenable: 1
      httpsport: 443
      harden: 0
      tlsmode: 3
      hsts: 1
      private_filename: "/tmp/private.key"
      signed_filename:  "/tmp/signed.key"
      inter_filename:   "/tmp/inter.key"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"

